# Generated by Django 3.2 on 2022-10-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptiveanswer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='answers/images/'),
        ),
        migrations.AlterField(
            model_name='descriptiveanswer',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
