# Generated by Django 3.2 on 2022-10-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='issue_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
