# Generated by Django 3.2 on 2023-02-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='institutional_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
