# Generated by Django 3.2 on 2023-01-06 17:57

from django.db import migrations, models
import django.db.models.deletion
import weeklies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.CharField(default=weeklies.models.Weekly.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('weeknum', models.IntegerField(unique=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pre_class_instruction', models.CharField(blank=True, max_length=2000, null=True)),
                ('in_class_instruction', models.CharField(blank=True, max_length=2000, null=True)),
                ('post_class_instruction', models.CharField(blank=True, max_length=2000, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='PreClassTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='PreClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(max_length=1000, upload_to=weeklies.models.PreClassFile.filepath)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='PostClassTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='PostClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(max_length=1000, upload_to=weeklies.models.PostClassFile.filepath)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='InClassTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='InClassFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(max_length=1000, upload_to=weeklies.models.InClassFile.filepath)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
    ]
