# Generated by Django 3.2 on 2023-01-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclasstutorial',
            name='yt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postclasstutorial',
            name='yt_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='preclasstutorial',
            name='yt_id',
            field=models.CharField(max_length=20),
        ),
    ]
