# Generated by Django 3.2 on 2023-01-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0002_auto_20230107_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='preclassfile',
            name='must_read',
            field=models.BooleanField(default=False),
        ),
    ]
