# Generated by Django 3.2 on 2022-12-28 17:05

from django.db import migrations, models
import weeklies.models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0002_auto_20221228_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inclassfile',
            name='attached_file',
            field=models.FileField(max_length=1000, upload_to=weeklies.models.InClassFile.filepath),
        ),
        migrations.AlterField(
            model_name='postclassfile',
            name='attached_file',
            field=models.FileField(max_length=1000, upload_to=weeklies.models.PostClassFile.filepath),
        ),
        migrations.AlterField(
            model_name='preclassfile',
            name='attached_file',
            field=models.FileField(max_length=1000, upload_to=weeklies.models.PreClassFile.filepath),
        ),
    ]
