# Generated by Django 3.2 on 2023-01-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0003_preclassfile_must_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preclassfile',
            old_name='must_read',
            new_name='must_study',
        ),
    ]
