# Generated by Django 3.2 on 2023-01-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0003_auto_20221228_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
