# Generated by Django 3.2 on 2023-01-13 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weeklies', '0005_auto_20230110_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forumpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcontent', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
    ]
