# Generated by Django 3.2 on 2023-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0006_forumpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly',
            name='weeknum',
            field=models.IntegerField(),
        ),
    ]
