# Generated by Django 3.2 on 2022-10-25 08:21

import classroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(default=classroom.models.Assignment.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('submission_deadline', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(default=classroom.models.Classroom.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomPost',
            fields=[
                ('id', models.CharField(default=classroom.models.ClassroomPost.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=9999)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to=classroom.models.PostAttachment.filepath)),
                ('classroom_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroompost')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=classroom.models.Comment.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=9999)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='classroom.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroompost')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to=classroom.models.AssignmentAttachment.filepath)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
