# Generated by Django 3.2 on 2023-01-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
