# Generated by Django 3.2 on 2023-02-03 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_classroom_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_marks', models.FloatField(default=10)),
                ('classtest_marks', models.FloatField(default=10)),
                ('group_task_marks', models.FloatField(default=5)),
                ('indiv_task_marks', models.FloatField(default=5)),
                ('weekly_test_marks', models.FloatField(default=10)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.FloatField(blank=True, null=True)),
                ('classtest_score', models.FloatField(blank=True, null=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assessmentmeta')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
