# Generated by Django 3.2 on 2022-10-14 18:37

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to=classroom.models.PostAttachment.filepath)),
                ('classroom_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroompost')),
            ],
        ),
    ]
