# Generated by Django 3.2 on 2023-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_assessment_assessmentmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='classrooms/banner/'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
