# Generated by Django 3.2 on 2023-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20230214_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
