# Generated by Django 3.2 on 2022-10-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_assignment_assignmentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
