# Generated by Django 3.2 on 2023-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroom_join_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmeta',
            name='group_task_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentmeta',
            name='indiv_task_marks',
        ),
        migrations.RemoveField(
            model_name='assessmentmeta',
            name='weekly_test_marks',
        ),
        migrations.AddField(
            model_name='assessmentmeta',
            name='in_class_marks',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='assessmentmeta',
            name='post_class_marks',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='assessmentmeta',
            name='pre_class_marks',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='assessmentmeta',
            name='classtest_marks',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
