# Generated by Django 3.2 on 2023-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_congratulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='congratulation',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
