# Generated by Django 3.2 on 2023-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_workattachment_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='submission_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
