# Generated by Django 3.2 on 2023-01-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_work_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
