# Generated by Django 3.2 on 2023-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_work_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
