# Generated by Django 3.2 on 2023-02-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_work_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
