# Generated by Django 3.2 on 2023-03-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeklies', '0007_alter_weekly_weeknum'),
        ('tasks', '0009_work_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weekly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly'),
        ),
    ]
