# Generated by Django 3.2 on 2023-01-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weekly_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weeklies', '0005_auto_20230110_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.CharField(default=weekly_test.models.AnswerSheet.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('issue_time', models.DateTimeField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTest',
            fields=[
                ('id', models.CharField(default=weekly_test.models.WeeklyTest.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('info', models.CharField(max_length=9999)),
                ('preclass', models.BooleanField(default=False)),
                ('inclass', models.BooleanField(default=False)),
                ('postclass', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField()),
                ('schedule', models.DateTimeField()),
                ('expiration', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weekly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeklies.weekly')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=99999)),
                ('marks', models.FloatField()),
                ('is_descriptive', models.BooleanField(default=False)),
                ('ans_as_img', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.weeklytest')),
            ],
        ),
        migrations.CreateModel(
            name='McqOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=9999)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.question')),
            ],
        ),
        migrations.CreateModel(
            name='McqAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.answersheet')),
                ('option_chosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.mcqoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.question')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=9999, null=True)),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='answers/images/')),
                ('score', models.FloatField(blank=True, null=True)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.answersheet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weekly_test.question')),
            ],
        ),
        migrations.AddField(
            model_name='answersheet',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weekly_test.weeklytest'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_test_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
